services:
  php:
    build:
      context: .
    image: symfony-app:${TAG}
    volumes:
      - .:/var/www
    environment:
      APP_ENV: prod
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: symfony       # Логин (должен совпадать с .env)
      POSTGRES_PASSWORD: mysecretpassword  # Пароль (должен совпадать с .env)
      POSTGRES_DB: todolis         # Название БД (должно совпадать с .env)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck: # Проверка готовности БД
      test: [ "CMD-SHELL", "pg_isready -U symfony -d todolis" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./logs:/var/log
      - ./docker/promtail-config.yaml:/etc/promtail/config.yaml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  grafana_data:
  postgres_data:
