name: Build and Deploy Symfony-Vue App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          TAG=${GITHUB_SHA::7}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/symfony-todo:${TAG} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/symfony-todo:${TAG}

      - name: Send Telegram notification
        uses: appleboy/telegram-action@v0.1.2
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✅ Build completed for commit ${{ github.sha }}
            🏷 Tag: ${{ github.sha::7 }}
            👤 Author: ${{ github.actor }}
